/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SHAKE_shake_device */

#ifndef _Included_SHAKE_shake_device
#define _Included_SHAKE_shake_device
#ifdef __cplusplus
extern "C" {
#endif
#undef SHAKE_shake_device_SHAKE_SK6
#define SHAKE_shake_device_SHAKE_SK6 0L
#undef SHAKE_shake_device_SHAKE_SK7
#define SHAKE_shake_device_SHAKE_SK7 1L
#undef SHAKE_shake_device_SHAKE_NAV_UP
#define SHAKE_shake_device_SHAKE_NAV_UP 1L
#undef SHAKE_shake_device_SHAKE_NAV_DOWN
#define SHAKE_shake_device_SHAKE_NAV_DOWN 2L
#undef SHAKE_shake_device_SHAKE_NAV_CENTRE
#define SHAKE_shake_device_SHAKE_NAV_CENTRE 3L
#undef SHAKE_shake_device_SHAKE_NAV_NORMAL
#define SHAKE_shake_device_SHAKE_NAV_NORMAL 4L
#undef SHAKE_shake_device_SHAKE_CS0_UPPER
#define SHAKE_shake_device_SHAKE_CS0_UPPER 5L
#undef SHAKE_shake_device_SHAKE_CS0_LOWER
#define SHAKE_shake_device_SHAKE_CS0_LOWER 6L
#undef SHAKE_shake_device_SHAKE_CS1_UPPER
#define SHAKE_shake_device_SHAKE_CS1_UPPER 7L
#undef SHAKE_shake_device_SHAKE_CS1_LOWER
#define SHAKE_shake_device_SHAKE_CS1_LOWER 8L
#undef SHAKE_shake_device_SHAKE_PLAYBACK_COMPLETE
#define SHAKE_shake_device_SHAKE_PLAYBACK_COMPLETE 9L
#undef SHAKE_shake_device_SHAKE_SHAKING_EVENT
#define SHAKE_shake_device_SHAKE_SHAKING_EVENT 10L
#undef SHAKE_shake_device_SHAKE_HEART_RATE_EVENT
#define SHAKE_shake_device_SHAKE_HEART_RATE_EVENT 11L
#undef SHAKE_shake_device_SHAKE_RFID_TID_EVENT
#define SHAKE_shake_device_SHAKE_RFID_TID_EVENT 12L
#undef SHAKE_shake_device_SHAKE_MODULE_NONE
#define SHAKE_shake_device_SHAKE_MODULE_NONE 0L
#undef SHAKE_shake_device_SHAKE_MODULE_GYRO1
#define SHAKE_shake_device_SHAKE_MODULE_GYRO1 1L
#undef SHAKE_shake_device_SHAKE_MODULE_GYRO2
#define SHAKE_shake_device_SHAKE_MODULE_GYRO2 2L
#undef SHAKE_shake_device_SHAKE_MODULE_RFID
#define SHAKE_shake_device_SHAKE_MODULE_RFID 3L
#undef SHAKE_shake_device_SHAKE_MODULE_AUDIO
#define SHAKE_shake_device_SHAKE_MODULE_AUDIO 4L
#undef SHAKE_shake_device_SHAKE_MODULE_EXTVIB
#define SHAKE_shake_device_SHAKE_MODULE_EXTVIB 5L
#undef SHAKE_shake_device_SHAKE_MODULE_USB
#define SHAKE_shake_device_SHAKE_MODULE_USB 6L
#undef SHAKE_shake_device_SHAKE_MODULE_EXPANSION
#define SHAKE_shake_device_SHAKE_MODULE_EXPANSION 7L
#undef SHAKE_shake_device_SHAKE_POWER_CAP
#define SHAKE_shake_device_SHAKE_POWER_CAP 1L
#undef SHAKE_shake_device_SHAKE_POWER_ACC
#define SHAKE_shake_device_SHAKE_POWER_ACC 2L
#undef SHAKE_shake_device_SHAKE_POWER_GYRO
#define SHAKE_shake_device_SHAKE_POWER_GYRO 4L
#undef SHAKE_shake_device_SHAKE_POWER_VIB
#define SHAKE_shake_device_SHAKE_POWER_VIB 8L
#undef SHAKE_shake_device_SHAKE_POWER_MAG
#define SHAKE_shake_device_SHAKE_POWER_MAG 16L
#undef SHAKE_shake_device_SHAKE_POWER_TEMP
#define SHAKE_shake_device_SHAKE_POWER_TEMP 32L
#undef SHAKE_shake_device_SHAKE_POWER_ANALOG
#define SHAKE_shake_device_SHAKE_POWER_ANALOG 64L
#undef SHAKE_shake_device_SHAKE_POWER_NAV
#define SHAKE_shake_device_SHAKE_POWER_NAV 128L
#undef SHAKE_shake_device_SHAKE_POWER_CS0_INC
#define SHAKE_shake_device_SHAKE_POWER_CS0_INC 1L
#undef SHAKE_shake_device_SHAKE_POWER_CS0_DEC
#define SHAKE_shake_device_SHAKE_POWER_CS0_DEC 2L
#undef SHAKE_shake_device_SHAKE_POWER_CS1_INC
#define SHAKE_shake_device_SHAKE_POWER_CS1_INC 4L
#undef SHAKE_shake_device_SHAKE_POWER_CS1_DEC
#define SHAKE_shake_device_SHAKE_POWER_CS1_DEC 8L
#undef SHAKE_shake_device_SHAKE_POWER_CS_EVENTS
#define SHAKE_shake_device_SHAKE_POWER_CS_EVENTS 16L
#undef SHAKE_shake_device_SHAKE_SENSOR_ACC
#define SHAKE_shake_device_SHAKE_SENSOR_ACC 0L
#undef SHAKE_shake_device_SHAKE_SENSOR_GYRO
#define SHAKE_shake_device_SHAKE_SENSOR_GYRO 1L
#undef SHAKE_shake_device_SHAKE_SENSOR_MAG
#define SHAKE_shake_device_SHAKE_SENSOR_MAG 2L
#undef SHAKE_shake_device_SHAKE_SENSOR_HEADING
#define SHAKE_shake_device_SHAKE_SENSOR_HEADING 3L
#undef SHAKE_shake_device_SHAKE_SENSOR_CAP0
#define SHAKE_shake_device_SHAKE_SENSOR_CAP0 4L
#undef SHAKE_shake_device_SHAKE_SENSOR_CAP1
#define SHAKE_shake_device_SHAKE_SENSOR_CAP1 5L
#undef SHAKE_shake_device_SHAKE_SENSOR_ANA0
#define SHAKE_shake_device_SHAKE_SENSOR_ANA0 6L
#undef SHAKE_shake_device_SHAKE_SENSOR_ANA1
#define SHAKE_shake_device_SHAKE_SENSOR_ANA1 7L
#undef SHAKE_shake_device_SHAKE_ACC_MAX_RATE
#define SHAKE_shake_device_SHAKE_ACC_MAX_RATE 255L
#undef SHAKE_shake_device_SHAKE_GYRO_MAX_RATE
#define SHAKE_shake_device_SHAKE_GYRO_MAX_RATE 255L
#undef SHAKE_shake_device_SHAKE_MAG_MAX_RATE
#define SHAKE_shake_device_SHAKE_MAG_MAX_RATE 255L
#undef SHAKE_shake_device_SHAKE_HEADING_MAX_RATE
#define SHAKE_shake_device_SHAKE_HEADING_MAX_RATE 255L
#undef SHAKE_shake_device_SHAKE_CAP0_MAX_RATE
#define SHAKE_shake_device_SHAKE_CAP0_MAX_RATE 255L
#undef SHAKE_shake_device_SHAKE_CAP1_MAX_RATE
#define SHAKE_shake_device_SHAKE_CAP1_MAX_RATE 255L
#undef SHAKE_shake_device_SHAKE_ANA0_MAX_RATE
#define SHAKE_shake_device_SHAKE_ANA0_MAX_RATE 255L
#undef SHAKE_shake_device_SHAKE_ANA1_MAX_RATE
#define SHAKE_shake_device_SHAKE_ANA1_MAX_RATE 255L
#undef SHAKE_shake_device_SHAKE_REQ_ACC
#define SHAKE_shake_device_SHAKE_REQ_ACC 1L
#undef SHAKE_shake_device_SHAKE_REQ_GYRO
#define SHAKE_shake_device_SHAKE_REQ_GYRO 2L
#undef SHAKE_shake_device_SHAKE_REQ_MAG
#define SHAKE_shake_device_SHAKE_REQ_MAG 4L
#undef SHAKE_shake_device_SHAKE_REQ_HEADING
#define SHAKE_shake_device_SHAKE_REQ_HEADING 8L
#undef SHAKE_shake_device_SHAKE_REQ_CAP0
#define SHAKE_shake_device_SHAKE_REQ_CAP0 16L
#undef SHAKE_shake_device_SHAKE_REQ_CAP1
#define SHAKE_shake_device_SHAKE_REQ_CAP1 32L
#undef SHAKE_shake_device_SHAKE_REQ_ANA0
#define SHAKE_shake_device_SHAKE_REQ_ANA0 64L
#undef SHAKE_shake_device_SHAKE_REQ_ANA1
#define SHAKE_shake_device_SHAKE_REQ_ANA1 128L
#undef SHAKE_shake_device_SHAKE_VIB_MAIN
#define SHAKE_shake_device_SHAKE_VIB_MAIN 0L
#undef SHAKE_shake_device_SHAKE_VIB_LEFT
#define SHAKE_shake_device_SHAKE_VIB_LEFT 1L
#undef SHAKE_shake_device_SHAKE_VIB_RIGHT
#define SHAKE_shake_device_SHAKE_VIB_RIGHT 2L
#undef SHAKE_shake_device_SHAKE_VIB_SAMPLE_MAX_LENGTH
#define SHAKE_shake_device_SHAKE_VIB_SAMPLE_MAX_LENGTH 32L
#undef SHAKE_shake_device_SHAKE_VIB_PROFILE_MIN
#define SHAKE_shake_device_SHAKE_VIB_PROFILE_MIN 1L
#undef SHAKE_shake_device_SHAKE_VIB_PROFILE_MAX
#define SHAKE_shake_device_SHAKE_VIB_PROFILE_MAX 255L
#undef SHAKE_shake_device_SHAKE_CALIB_MAG
#define SHAKE_shake_device_SHAKE_CALIB_MAG 1L
#undef SHAKE_shake_device_SHAKE_CALIB_ACC
#define SHAKE_shake_device_SHAKE_CALIB_ACC 2L
#undef SHAKE_shake_device_SHAKE_CALIB_GYRO
#define SHAKE_shake_device_SHAKE_CALIB_GYRO 3L
#undef SHAKE_shake_device_SHAKE_CALIB_TEMP
#define SHAKE_shake_device_SHAKE_CALIB_TEMP 4L
#undef SHAKE_shake_device_SHAKE_CALIB_BATTERY
#define SHAKE_shake_device_SHAKE_CALIB_BATTERY 5L
#undef SHAKE_shake_device_SHAKE_CALIB_CAP
#define SHAKE_shake_device_SHAKE_CALIB_CAP 6L
#undef SHAKE_shake_device_SHAKE_CALIB_ANALONG
#define SHAKE_shake_device_SHAKE_CALIB_ANALONG 7L
#undef SHAKE_shake_device_SHAKE_BYPASS_ACC
#define SHAKE_shake_device_SHAKE_BYPASS_ACC 1L
#undef SHAKE_shake_device_SHAKE_BYPASS_GYRO
#define SHAKE_shake_device_SHAKE_BYPASS_GYRO 2L
#undef SHAKE_shake_device_SHAKE_BYPASS_MAG
#define SHAKE_shake_device_SHAKE_BYPASS_MAG 4L
#undef SHAKE_shake_device_SHAKE_BYPASS_CAP0
#define SHAKE_shake_device_SHAKE_BYPASS_CAP0 16L
#undef SHAKE_shake_device_SHAKE_BYPASS_CAP1
#define SHAKE_shake_device_SHAKE_BYPASS_CAP1 32L
#undef SHAKE_shake_device_SHAKE_BYPASS_ANA0
#define SHAKE_shake_device_SHAKE_BYPASS_ANA0 64L
#undef SHAKE_shake_device_SHAKE_BYPASS_ANA1
#define SHAKE_shake_device_SHAKE_BYPASS_ANA1 128L
#undef SHAKE_shake_device_SHAKE_CX_BYPASS_ACC
#define SHAKE_shake_device_SHAKE_CX_BYPASS_ACC 1L
#undef SHAKE_shake_device_SHAKE_CX_BYPASS_GYRO
#define SHAKE_shake_device_SHAKE_CX_BYPASS_GYRO 2L
#undef SHAKE_shake_device_SHAKE_CX_BYPASS_MAG
#define SHAKE_shake_device_SHAKE_CX_BYPASS_MAG 4L
#undef SHAKE_shake_device_SHAKE_STREAM_ACC
#define SHAKE_shake_device_SHAKE_STREAM_ACC 1L
#undef SHAKE_shake_device_SHAKE_STREAM_GYRO
#define SHAKE_shake_device_SHAKE_STREAM_GYRO 2L
#undef SHAKE_shake_device_SHAKE_STREAM_MAG
#define SHAKE_shake_device_SHAKE_STREAM_MAG 4L
#undef SHAKE_shake_device_SHAKE_STREAM_HEADING
#define SHAKE_shake_device_SHAKE_STREAM_HEADING 8L
#undef SHAKE_shake_device_SHAKE_STREAM_CAP0
#define SHAKE_shake_device_SHAKE_STREAM_CAP0 16L
#undef SHAKE_shake_device_SHAKE_STREAM_CAP1
#define SHAKE_shake_device_SHAKE_STREAM_CAP1 32L
#undef SHAKE_shake_device_SHAKE_STREAM_ANA0
#define SHAKE_shake_device_SHAKE_STREAM_ANA0 64L
#undef SHAKE_shake_device_SHAKE_STREAM_ANA1
#define SHAKE_shake_device_SHAKE_STREAM_ANA1 128L
#undef SHAKE_shake_device_SHAKE_EXT_POWER
#define SHAKE_shake_device_SHAKE_EXT_POWER 1L
#undef SHAKE_shake_device_SHAKE_BAT_CHARGING
#define SHAKE_shake_device_SHAKE_BAT_CHARGING 2L
#undef SHAKE_shake_device_SHAKE_BAT_FULL
#define SHAKE_shake_device_SHAKE_BAT_FULL 4L
#undef SHAKE_shake_device_SHAKE_BATTERY_MAX
#define SHAKE_shake_device_SHAKE_BATTERY_MAX 255L
#undef SHAKE_shake_device_SHAKE_TEMP_MIN
#define SHAKE_shake_device_SHAKE_TEMP_MIN 0L
#undef SHAKE_shake_device_SHAKE_TEMP_MAX
#define SHAKE_shake_device_SHAKE_TEMP_MAX 64L
#undef SHAKE_shake_device_SHAKE_LOGGING_PLAY
#define SHAKE_shake_device_SHAKE_LOGGING_PLAY 1L
#undef SHAKE_shake_device_SHAKE_LOGGING_PAUSE
#define SHAKE_shake_device_SHAKE_LOGGING_PAUSE 2L
#undef SHAKE_shake_device_SHAKE_LOGGING_STOP
#define SHAKE_shake_device_SHAKE_LOGGING_STOP 3L
#undef SHAKE_shake_device_SHAKE_LOGGING_RECORD
#define SHAKE_shake_device_SHAKE_LOGGING_RECORD 4L
#undef SHAKE_shake_device_SHAKE_LOGGING_RESET
#define SHAKE_shake_device_SHAKE_LOGGING_RESET 5L
#undef SHAKE_shake_device_SHAKE_LOGGING_RECORDING
#define SHAKE_shake_device_SHAKE_LOGGING_RECORDING 1L
#undef SHAKE_shake_device_SHAKE_LOGGING_PLAYING
#define SHAKE_shake_device_SHAKE_LOGGING_PLAYING 2L
#undef SHAKE_shake_device_SHAKE_LOGGING_MEMORYFULL
#define SHAKE_shake_device_SHAKE_LOGGING_MEMORYFULL 4L
#undef SHAKE_shake_device_SHAKE_SHAKING_DETECTION
#define SHAKE_shake_device_SHAKE_SHAKING_DETECTION 1L
#undef SHAKE_shake_device_SHAKE_SHAKING_DIRECTION_DETECTION
#define SHAKE_shake_device_SHAKE_SHAKING_DIRECTION_DETECTION 2L
#undef SHAKE_shake_device_SHAKE_SHAKING_VIBRATION
#define SHAKE_shake_device_SHAKE_SHAKING_VIBRATION 4L
#undef SHAKE_shake_device_SHAKE_AUDIO_SAMPLING
#define SHAKE_shake_device_SHAKE_AUDIO_SAMPLING 1L
#undef SHAKE_shake_device_SHAKE_AUDIO_PLAYBACK
#define SHAKE_shake_device_SHAKE_AUDIO_PLAYBACK 2L
#undef SHAKE_shake_device_SHAKE_AUDIO_EXTERNAL_MIC
#define SHAKE_shake_device_SHAKE_AUDIO_EXTERNAL_MIC 4L
#undef SHAKE_shake_device_SHAKE_AUDIO_DATA_LEN
#define SHAKE_shake_device_SHAKE_AUDIO_DATA_LEN 32L
#undef SHAKE_shake_device_SHAKE_AUDIO_SAMPLE_RATE
#define SHAKE_shake_device_SHAKE_AUDIO_SAMPLE_RATE 7200L
#undef SHAKE_shake_device_SHAKE_AUDIO_SAMPLE_SIZE
#define SHAKE_shake_device_SHAKE_AUDIO_SAMPLE_SIZE 16L
#undef SHAKE_shake_device_SHAKE_MIDI_AMPLITUDE_MUTE
#define SHAKE_shake_device_SHAKE_MIDI_AMPLITUDE_MUTE 0L
#undef SHAKE_shake_device_SHAKE_MIDI_AMPLITUDE_MIN
#define SHAKE_shake_device_SHAKE_MIDI_AMPLITUDE_MIN 1L
#undef SHAKE_shake_device_SHAKE_MIDI_AMPLITUDE_MAX
#define SHAKE_shake_device_SHAKE_MIDI_AMPLITUDE_MAX 255L
#undef SHAKE_shake_device_SHAKE_MIDI_NOTE_MIN
#define SHAKE_shake_device_SHAKE_MIDI_NOTE_MIN 33L
#undef SHAKE_shake_device_SHAKE_MIDI_NOTE_MAX
#define SHAKE_shake_device_SHAKE_MIDI_NOTE_MAX 105L
#undef SHAKE_shake_device_SHAKE_MIDI_WAVEFORM_SINE
#define SHAKE_shake_device_SHAKE_MIDI_WAVEFORM_SINE 0L
#undef SHAKE_shake_device_SHAKE_MIDI_WAVEFORM_SQUARE
#define SHAKE_shake_device_SHAKE_MIDI_WAVEFORM_SQUARE 1L
#undef SHAKE_shake_device_SHAKE_MIDI_WAVEFORM_TRIANGLE
#define SHAKE_shake_device_SHAKE_MIDI_WAVEFORM_TRIANGLE 2L
#undef SHAKE_shake_device_SHAKE_MIDI_WAVEFORM_SAWTOOTH
#define SHAKE_shake_device_SHAKE_MIDI_WAVEFORM_SAWTOOTH 3L
#undef SHAKE_shake_device_SHAKE_AUDIO_PAGE_SIZE
#define SHAKE_shake_device_SHAKE_AUDIO_PAGE_SIZE 1056L
#undef SHAKE_shake_device_SHAKE_AUDIO_AMPLITUDE_MIN
#define SHAKE_shake_device_SHAKE_AUDIO_AMPLITUDE_MIN 0L
#undef SHAKE_shake_device_SHAKE_AUDIO_AMPLITUDE_MAX
#define SHAKE_shake_device_SHAKE_AUDIO_AMPLITUDE_MAX 255L
#undef SHAKE_shake_device_SHAKE_AUDIO_UPLOAD_MIN
#define SHAKE_shake_device_SHAKE_AUDIO_UPLOAD_MIN 0L
#undef SHAKE_shake_device_SHAKE_AUDIO_UPLOAD_MAX
#define SHAKE_shake_device_SHAKE_AUDIO_UPLOAD_MAX 7999L
/*
 * Class:     SHAKE_shake_device
 * Method:    shake_init_device
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_SHAKE_shake_1device_shake_1init_1device
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_init_device_rfcomm
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_SHAKE_shake_1device_shake_1init_1device_1rfcomm
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_free_device
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1free_1device
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_info_firmware_revision
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_SHAKE_shake_1device_shake_1info_1firmware_1revision
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_info_hardware_revision
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_SHAKE_shake_1device_shake_1info_1hardware_1revision
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_info_serial_number
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SHAKE_shake_1device_shake_1info_1serial_1number
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_info_module_slot1
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1info_1module_1slot1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_info_module_slot2
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1info_1module_1slot2
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_info_retrieve
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1info_1retrieve
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_info_module_name
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SHAKE_shake_1device_shake_1info_1module_1name
  (JNIEnv *, jclass, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_accx
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1accx
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_accy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1accy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_accz
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1accz
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_acc
 * Signature: (J[I)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1acc
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_gyrx
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1gyrx
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_gyry
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1gyry
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_gyrz
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1gyrz
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_gyr
 * Signature: (J[I)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1gyr
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_magx
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1magx
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_magy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1magy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_magz
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1magz
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_mag
 * Signature: (J[I)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1mag
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_heading
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1heading
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_cap0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1cap0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_cap1
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1cap1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_cap
 * Signature: (J[I)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1cap
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_analog0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1analog0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_analog1
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1analog1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_analog
 * Signature: (J[I)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1analog
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_shaking_peakaccel
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1shaking_1peakaccel
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_shaking_direction
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1shaking_1direction
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_shaking_timestamp
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1shaking_1timestamp
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    sk7_roll_pitch_heading
 * Signature: (J[I)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_sk7_1roll_1pitch_1heading
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     SHAKE_shake_device
 * Method:    sk7_roll_pitch_heading_quaternions
 * Signature: (J[I)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_sk7_1roll_1pitch_1heading_1quaternions
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     SHAKE_shake_device
 * Method:    sk7_configure_roll_pitch_heading
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_sk7_1configure_1roll_1pitch_1heading
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_register_event_callback
 * Signature: (Ljava/lang/Object;J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1register_1event_1callback
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_data_timestamp
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1data_1timestamp
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_logging_play
 * Signature: (J[C)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1logging_1play
  (JNIEnv *, jclass, jlong, jcharArray);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_logging_pause
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1logging_1pause
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_logging_stop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1logging_1stop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_logging_record
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1logging_1record
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_logging_reset
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1logging_1reset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_logging_status
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1logging_1status
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_logging_memory_status
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1logging_1memory_1status
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_logging_packet_count
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1logging_1packet_1count
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_logging_packets_read
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1logging_1packets_1read
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_read_power_state
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1read_1power_1state
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_write_power_state
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1write_1power_1state
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_read_power_state_2
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1read_1power_1state_12
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_write_power_state_2
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1write_1power_1state_12
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_read_acc_config
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1read_1acc_1config
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_write_acc_config
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1write_1acc_1config
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_read_data_format
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1read_1data_1format
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_write_data_format
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1write_1data_1format
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_read_sample_rate
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1read_1sample_1rate
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_write_sample_rate
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1write_1sample_1rate
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_read_digital_filter
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1read_1digital_1filter
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_write_digital_filter
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1write_1digital_1filter
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_read_calib_bypass
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1read_1calib_1bypass
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_write_calib_bypass
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1write_1calib_1bypass
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_read_cx_bypass
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1read_1cx_1bypass
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_write_cx_bypass
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1write_1cx_1bypass
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_read_temp_compensation
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1read_1temp_1compensation
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_write_temp_compensation
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1write_1temp_1compensation
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_read_packet_streaming
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1read_1packet_1streaming
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_write_packet_streaming
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1write_1packet_1streaming
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_read_audio_config
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1read_1audio_1config
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_write_audio_config
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1write_1audio_1config
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_write_midi_amplitude
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1write_1midi_1amplitude
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_write_midi_note
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1write_1midi_1note
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_write_midi_waveform
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1write_1midi_1waveform
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    sk6_read_cs0_inc
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_sk6_1read_1cs0_1inc
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    sk6_write_cs0_inc
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_sk6_1write_1cs0_1inc
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    sk6_read_cs0_dec
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_sk6_1read_1cs0_1dec
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    sk6_write_cs0_dec
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_sk6_1write_1cs0_1dec
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    sk6_read_cs0_inc_profile
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_sk6_1read_1cs0_1inc_1profile
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    sk6_write_cs0_inc_profile
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_sk6_1write_1cs0_1inc_1profile
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    sk6_read_cs0_dec_profile
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_sk6_1read_1cs0_1dec_1profile
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    sk6_write_cs0_dec_profile
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_sk6_1write_1cs0_1dec_1profile
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    sk6_read_cs1_inc
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_sk6_1read_1cs1_1inc
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    sk6_write_cs1_inc
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_sk6_1write_1cs1_1inc
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    sk6_read_cs1_dec
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_sk6_1read_1cs1_1dec
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    sk6_write_cs1_dec
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_sk6_1write_1cs1_1dec
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    sk6_read_cs1_inc_profile
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_sk6_1read_1cs1_1inc_1profile
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    sk6_write_cs1_inc_profile
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_sk6_1write_1cs1_1inc_1profile
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    sk6_read_cs1_dec_profile
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_sk6_1read_1cs1_1dec_1profile
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    sk6_write_cs1_dec_profile
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_sk6_1write_1cs1_1dec_1profile
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    sk6_read_cap_thresholds
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_sk6_1read_1cap_1thresholds
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     SHAKE_shake_device
 * Method:    sk6_write_cap_thresholds
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_sk6_1write_1cap_1thresholds
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_read_shaking_config
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1read_1shaking_1config
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_write_shaking_config
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1write_1shaking_1config
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_read_shaking_accel_threshold
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1read_1shaking_1accel_1threshold
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_write_shaking_accel_threshold
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1write_1shaking_1accel_1threshold
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_read_shaking_holdoff_time
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1read_1shaking_1holdoff_1time
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_write_shaking_holdoff_time
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1write_1shaking_1holdoff_1time
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_read_shaking_vibration_profile
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1read_1shaking_1vibration_1profile
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_write_shaking_vibration_profile
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1write_1shaking_1vibration_1profile
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_read_shaking_hpf_constant
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1read_1shaking_1hpf_1constant
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_write_shaking_hpf_constant
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1write_1shaking_1hpf_1constant
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_read_shaking_lpf_constant
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1read_1shaking_1lpf_1constant
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_write_shaking_lpf_constant
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1write_1shaking_1lpf_1constant
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_reset_shaking_detection
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1reset_1shaking_1detection
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_write_packet_request
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1write_1packet_1request
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_write_data_request
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1write_1data_1request
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_playvib
 * Signature: (JIB)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1playvib
  (JNIEnv *, jclass, jlong, jint, jbyte);

/*
 * Class:     SHAKE_shake_device
 * Method:    sk6_upload_vib_sample
 * Signature: (JB[I)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_sk6_1upload_1vib_1sample
  (JNIEnv *, jclass, jlong, jbyte, jintArray);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_read_battery_level
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1read_1battery_1level
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_read_power_status
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1read_1power_1status
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_read_temperature
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_SHAKE_shake_1device_shake_1read_1temperature
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_read
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1read
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SHAKE_shake_device
 * Method:    shake_write
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_SHAKE_shake_1device_shake_1write
  (JNIEnv *, jclass, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
